# Generated by Django 5.1.4 on 2025-01-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Vinyl',
        ),
    ]
