# Generated by Django 5.1.4 on 2025-01-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_vinyl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyl',
            old_name='breed',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='vinyl',
            old_name='age',
            new_name='release',
        ),
    ]
