# Generated by Django 5.1.4 on 2025-01-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_breed_vinyl_category_rename_age_vinyl_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('format', models.CharField(choices=[('LP', 'Long Play'), ('EP', 'Extended Play'), ('SG', 'Single')], default='LP', max_length=2)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vinyl')),
            ],
        ),
    ]
