# Generated by Django 5.1.4 on 2025-01-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinyl',
            name='played_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='vinyl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='main_app.vinyl'),
        ),
    ]
