# Generated by Django 5.1.4 on 2025-01-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_genre_options_genre_name_vinyl_played_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='release_date',
        ),
    ]
