# Generated by Django 5.1.4 on 2025-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_genre_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='release',
        ),
        migrations.AddField(
            model_name='vinyl',
            name='release_date',
            field=models.DateField(default='2000-12-12', verbose_name='Release Date'),
            preserve_default=False,
        ),
    ]
