# Generated by Django 5.1.4 on 2025-01-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_vinyl_release_vinyl_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyl',
            old_name='release_date',
            new_name='release',
        ),
    ]
