# Generated by Django 5.1.4 on 2025-01-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_release_date_vinyl_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='category',
        ),
    ]
