# Generated by Django 5.1.4 on 2025-01-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_vinyl_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='release_date',
            field=models.DateField(default='2000-12-12', verbose_name='Release Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinyl',
            name='category',
            field=models.CharField(default='default value', max_length=100),
            preserve_default=False,
        ),
    ]
