# Generated by Django 5.1.4 on 2025-01-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_genre_release_date_vinyl_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='vinyl',
            name='category',
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='release',
            field=models.DateField(verbose_name='Release Date'),
        ),
    ]
