# Generated by Django 5.1.4 on 2025-01-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_genre_release_date_remove_vinyl_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyl',
            old_name='release',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='vinyl',
            name='category',
            field=models.CharField(default='YYYY-MM-DD', max_length=100),
            preserve_default=False,
        ),
    ]
