# Generated by Django 5.1.4 on 2025-01-14 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_release_vinyl_release_date_vinyl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text='Duration in format MM:SS', max_length=5)),
                ('side', models.CharField(choices=[('A', 'Side A'), ('B', 'Side B'), ('C', 'Side C'), ('D', 'Side D')], default='A', max_length=1)),
                ('position', models.PositiveIntegerField(help_text='Track number on the side', validators=[django.core.validators.MinValueValidator(1)])),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('composer', models.CharField(blank=True, max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='main_app.vinyl')),
            ],
            options={
                'ordering': ['vinyl', 'side', 'position'],
            },
        ),
    ]
