# Generated by Django 5.1.4 on 2025-01-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='vinyl',
        ),
        migrations.AddField(
            model_name='vinyl',
            name='tracks',
            field=models.ManyToManyField(to='main_app.track'),
        ),
    ]
